---
title: Video Games!
author: Jason Rappazzo
date: '2022-11-08'
slug: video-games
categories: []
tags:
  - R
  - R Markdown
  - Wii
  - Graphs
---

Video games were a large part of my childhood especially playing on the Wii. One of my all time favorite games was Super Mario Galaxy. There was also Wii Sports, Tony Hawk's Downhill Jam, and the early Call of Duty Games. I have spent countless early mornings and many late nights playing video games. Though I have not played many video games in the past few years, they will always have a special place in my heart. 

Video games have a massive market. It was valued at [**195 billion (USD)**](https://www.grandviewresearch.com/industry-analysis/video-game-market#:~:text=Report%20Overview,12.9%25%20from%202022%20to%202030.) in 2021! General trends indicate strong positive trends going forward. This brought up a few questions to me. 

* Which video game brought in the most amount of global sales?
* Which year had the highest total sales across all video games?
* Was there a dominant publisher that had the most sales?
* Is there a particular console that generated the most sales?

To answer these questions, I will be looking at this [**dataset**](https://www.kaggle.com/datasets/gregorut/videogamesales) to find the answers.
